version: '3.8'

services:
  backend:
    build: .
    depends_on:
      - mongo
      - minio
    env_file:
      - .env
    ports:
      - "8000:8000"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "8081:8081"

  minio:
    image: minio/minio
    command: server /data
    env_file:
      - .env
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"

volumes:
  mongo_data:
  minio_data:
